name: shared_constants
description: Shared constants package for petfood projects (petfood_development, petfooder, Firebase Functions)
version: 1.0.0
homepage: https://github.com/username/shared_constants_package

environment:
  sdk: ^3.5.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: